### ISSUE TITLE
Typo in output file

### ISSUE THREAD

**Issue by DonLocke** [polyrod/xnec2c-gao#16]
https://github.com/polyrod/xnec2c-gao/blob/b2eb3b856dfacd3a26387fdf48bac25e52ec2cbf/app/Output.hs#L79

Is this meant to be `AVSWR` ?

**Comment by polyrod** [comment]
Yes, of course. Thank you, will fix.

**Comment by polyrod** [comment]
Fixed in https://github.com/polyrod/xnec2c-gao/commit/9a492a1c07da9c6fb8ee9effdb7f92ff69b9d862
